###
http://localhost:8081


###

GET http://localhost:8081/pair HTTP/1.1
Content-Type: "application/json"

{
    "pairName":"USDT:WETH"
}


###
POST http://localhost:8081/createPair HTTP/1.1
Content-Type: "application/json"


{
    "XToken":{
        "name":"USDT",
        "balance":10,
        "address":"0xb"
    },
    "YToken":{
        "name":"WETH",
        "balance":200,
        "address":"0xb"
    }
}



###

POST http://localhost:8081/deposit HTTP/1.1
Content-Type: "application/json"

{
    "pairName":"USDT:WETH",
    "XToken":{
        "name":"USDT",
        "balance":11,
        "address":"0xa"
    },
    "YToken":{
        "name":"WETH",
        "balance":200,
        "address":"0xa"
    }
}

###
POST http://localhost:8081/withdraw HTTP/1.1
Content-Type: "application/json"

{
    "pairName":"USDT:WETH",
    "account":"0xa",
    "amount":10
}

###
POST http://localhost:8081/swap HTTP/1.1
Content-Type: "application/json"

{
    "pairName":"USDT:WETH",
    "tokenName":"USDT",
    "account":"0xc",
    "amount":10
}